### ISSUE TITLE
failed to open stream: No such file or directory 

### ISSUE THREAD

**Issue by chokri** [Grafikart/CakePHP-ImageHelper#5]
ok, j'ai testé et ça bug chez moi, il m'affiche une belle erreur:
`Warning (2): getimagesize(C:\wamp\www\cake\app\webroot\img\img/uploads/2014/09/dahouse.jpg) [function.getimagesize]: failed to open stream: No such file or directory [APP\View\Helper\ImageHelper.php, line 63]`

si je développe Warning ça affiche:
`getimagesize - [internal], line ??
ImageHelper::resizedUrl() - APP\View\Helper\ImageHelper.php, line 63
ImageHelper::resize() - APP\View\Helper\ImageHelper.php, line 37
include - APP\View\Biens\view.ctp, line 4
View::_evaluate() - CORE\Cake\View\View.php, line 948
View::_render() - CORE\Cake\View\View.php, line 910
View::render() - CORE\Cake\View\View.php, line 471
Controller::render() - CORE\Cake\Controller\Controller.php, line 954
Dispatcher::_invoke() - CORE\Cake\Routing\Dispatcher.php, line 198
Dispatcher::dispatch() - CORE\Cake\Routing\Dispatcher.php, line 165
[main] - APP\webroot\index.php, line 108`
Conseil? ou astuce? resultat debugué `<img src="/cake/img/" quality="100" width="400" height="250" alt="" />`

**Comment by leknoppix** [comment]
Regarde ton getimagesize, tu vas 2 fois dans img!!

**Comment by chokri** [comment]
Ça m'a pris un peut de temps pour se souvenir de cet erreur, c'était une erreur lié au DS et non pas CakePHP.
